### PR TITLE
RK-6476 - added git params to assembly

### PR DESCRIPTION
**Pull request by ElDuderinos**
added according to deployment example https://github.com/Rookout/deployment-examples/blob/master/dotnet-aspnet/dotnet-core-3/SimpleHttpServer.csproj

### CODE REVIEW

**Comment by ElDuderinos** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Review by BenTheKlein — APPROVED** [review]

**Comment by ElDuderinos** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Comment by ElDuderinos** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Comment by ElDuderinos** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Comment by MickaelAlliel** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Comment by ElDuderinos** [comment]
Github Enforcer opened Task: [RK-6476](https://rookout.atlassian.net/projects/RK/issues/RK-6476)

**Pull request merged**
